#!/usr/bin/env python3
"""Create a private Tag configuration without storing secrets in Git."""

from __future__ import annotations

import argparse
import getpass
import os
import shlex
import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


@dataclass(frozen=True)
class BackendOption:
    key: str
    name: str
    note: str
    install_url: str


BACKEND_OPTIONS = (
    BackendOption(
        key="codex",
        name="Codex",
        note="Recommended and supported",
        install_url="https://learn.chatgpt.com/docs/codex/cli",
    ),
    BackendOption(
        key="claude",
        name="Claude Code",
        note="Experimental",
        install_url="https://code.claude.com/docs/en/setup",
    ),
)


def runtime_requirement(package: str) -> str:
    requirements = ROOT / "requirements-runtime.txt"
    prefix = f"{package}=="
    for raw_line in requirements.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if line.startswith(prefix):
            return line
    raise RuntimeError(f"{requirements} does not pin {package}")


def ask(prompt: str, default: str | None = None) -> str:
    suffix = f" [{default}]" if default else ""
    value = input(f"{prompt}{suffix}: ").strip()
    return value or (default or "")


def ask_required(prompt: str) -> str:
    while True:
        value = ask(prompt)
        if value:
            return value
        print("A value is required.")


def choose_backend() -> str:
    print("Choose the local agent that will run Tag tasks:\n")
    for index, option in enumerate(BACKEND_OPTIONS, start=1):
        availability = "installed" if shutil.which(option.key) else "not found"
        print(f"  {index}. {option.name:<12} {option.note:<27} {availability}")

    aliases = {
        "1": "codex",
        "codex": "codex",
        "2": "claude",
        "claude": "claude",
        "claude code": "claude",
    }
    while True:
        answer = ask("\nAgent", "1").lower()
        backend = aliases.get(answer)
        if backend:
            return backend
        print("Choose 1 for Codex or 2 for Claude Code.")


def selected_backend_available(backend: str) -> bool:
    option = next(option for option in BACKEND_OPTIONS if option.key == backend)
    if shutil.which(option.key):
        return True

    print(f"\n{option.name} was selected, but `{option.key}` is not available on PATH.")
    print(f"Install and sign in first: {option.install_url}")
    print("Then run ./tag setup again.")
    return False


def ask_secret(prompt: str, prefix: str) -> str:
    while True:
        value = getpass.getpass(f"{prompt}: ").strip()
        if value.startswith(prefix):
            return value
        print(f"Enter the {prefix} token issued by Slack.")


def confirm(prompt: str, default: bool = True) -> bool:
    choice = "Y/n" if default else "y/N"
    answer = input(f"{prompt} [{choice}]: ").strip().lower()
    return default if not answer else answer in {"y", "yes"}


def check_prerequisites(backend: str) -> bool:
    ok = True
    for command, purpose in (("uv", "Python dependency runner"), (backend, "selected CLI backend")):
        found = shutil.which(command)
        print(f"{'✓' if found else '✗'} {command}: {purpose}")
        ok = ok and bool(found)

    if not shutil.which("mfs-server"):
        print("✗ mfs-server: MFS memory server")
        mfs_server_spec = runtime_requirement("mfs-server")
        if shutil.which("uv") and confirm(f"Install {mfs_server_spec} with uv now?"):
            completed = subprocess.run(
                ["uv", "tool", "install", "--force", mfs_server_spec], check=False
            )
            ok = ok and completed.returncode == 0 and shutil.which("mfs-server") is not None
        else:
            ok = False
    else:
        print("✓ mfs-server: MFS memory server")
    return ok


def absolute_directory(prompt: str, default: Path) -> Path:
    while True:
        value = Path(ask(prompt, str(default))).expanduser()
        if value.is_dir():
            return value.resolve()
        print("That directory does not exist. Create it first or choose an existing workspace.")


def render_env(values: dict[str, str]) -> str:
    lines = [
        "# Generated by scripts/opentag_setup.py. Keep this file private.",
        "# It is ignored by Git and is limited to this account (chmod 600).",
        "",
    ]
    for key, value in values.items():
        lines.append(f"export {key}={shlex.quote(value)}")
    lines.append("")
    return "\n".join(lines)


def write_config(path: Path, values: dict[str, str]) -> None:
    path.write_text(render_env(values))
    path.chmod(0o600)
    print(f"\nWrote private configuration: {path}")


def main() -> int:
    parser = argparse.ArgumentParser(description="Guided Tag first-run setup.")
    parser.add_argument("--config", type=Path, default=ROOT / ".env", help="configuration file to create")
    parser.add_argument("--force", action="store_true", help="replace an existing configuration file")
    args = parser.parse_args()
    config_path = args.config.expanduser().resolve()

    if config_path.exists() and not args.force:
        print(f"Refusing to overwrite existing configuration: {config_path}")
        print("Use --force only after backing up values you want to keep.")
        return 1

    print("Tag guided setup\n")
    print("Provider authorization stays in your own browser and terminal.\n")
    backend = choose_backend()
    if not selected_backend_available(backend):
        return 1
    workspace = absolute_directory("Workspace the agent may use", ROOT)
    mfs_scope = ask("Allowed MFS scopes (comma-separated)", f"file://local{workspace}")
    values = {
        "MFS_URL": ask("MFS URL", "http://127.0.0.1:13619"),
        "MFS_ALLOWED_SCOPES": mfs_scope,
        "OPENTAG_BACKEND": backend,
        "OPENTAG_BOT_NAME": ask("Bot display name", "OpenMax"),
        "OPENTAG_WORKDIR": str(workspace),
        "OPENTAG_TIMEOUT_SECONDS": ask("Per-task timeout in seconds", "420"),
        "OPENTAG_BACKEND_ATTEMPTS": ask("Backend retry attempts", "3"),
        "OPENTAG_TRANSPORT": "slack",
    }
    print("\nCreate the Slack app from slack-app-manifest.yaml:")
    print("  https://api.slack.com/apps → Create New App → From an app manifest")
    print("Then install it, enable Socket Mode, and create an app token with connections:write.")
    values["SLACK_APP_TOKEN"] = ask_secret("Slack app token", "xapp-")
    values["SLACK_BOT_TOKEN"] = ask_secret("Slack bot token", "xoxb-")
    values["SLACK_CHANNEL_ID"] = ask("Optional sandbox Slack channel ID")
    print("In Slack, open your profile, choose More, then Copy member ID.")
    values["SLACK_ALLOWED_USER_IDS"] = ask_required("Owner Slack member ID")
    values["OPENTAG_SLACK_STREAMING"] = "1"

    write_config(config_path, values)
    print("\nChecking local prerequisites:")
    prerequisites_ok = check_prerequisites(backend)
    print("\nNext steps:")
    print("1. Add/index at least one source in MFS that matches MFS_ALLOWED_SCOPES.")
    print("2. Run ./tag start. It starts MFS, runs preflight, and starts the bot.")
    print("3. Mention the bot in the configured sandbox channel.")
    if not prerequisites_ok:
        print("\nFinish the failed prerequisite checks before starting Tag.")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
